using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CSharp;
using xCodeGen.Abstractions.Attributes;
using xCodeGen.Abstractions.Extractors;
using xCodeGen.Abstractions.Metadata;

namespace xCodeGen.SourceGenerator
{
    public partial class CodeMetaDataExtractor
    {
        // 代码生成常量定义
        public const string GeneratedFileExtension = ".g.cs";
        public const string MetaFilePrefix = "Meta/";
        public const string InterfaceFilePrefix = "Interfaces/";
        public const string DecoratorFilePrefix = "Decorators/";
        public const string DefaultTemplateName = "Default";
        public const string AutoGeneratedHeader = @"// <auto-generated/>
// 自动生成代码，请勿手动修改
// 生成器: CodeMetaDataExtractor
// 生成时间: {0:yyyy-MM-dd HH:mm:ss}
#nullable enable
";

        /// <summary>
        /// 异步提取元数据（源生成器环境中建议使用同步Extract方法，此方法仅为接口兼容）
        /// </summary>
        public Task<IEnumerable<RawMetadata>> ExtractAsync(ExtractorOptions options, CancellationToken cancellationToken = default)
        {
            // 源生成器环境下不推荐使用文件系统操作
            throw new NotImplementedException("源生成器环境建议使用同步Extract(Compilation)方法");
        }

        #region --- Helper Functions (Std 2.0 兼容) ---

        private AttributeMetadata FindAttribute(IEnumerable<AttributeMetadata> attrs, string targetName)
        {
            if (attrs == null) return null;
            foreach (var a in attrs)
            {
                if (!string.IsNullOrEmpty(a.TypeFullName) &&
                    a.TypeFullName.IndexOf(targetName, StringComparison.OrdinalIgnoreCase) >= 0)
                    return a;
            }
            return null;
        }

        private bool ImplementsInterface(ClassMetadata m, string interfaceName)
        {
            if (m.ImplementedInterfaces == null) return false;
            foreach (var i in m.ImplementedInterfaces)
            {
                if (!string.IsNullOrEmpty(i) &&
                    i.IndexOf(interfaceName, StringComparison.OrdinalIgnoreCase) >= 0)
                    return true;
            }
            return false;
        }

        private static string GetGenerateMode(INamedTypeSymbol symbol) { var attr = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == DomainGenerateCodeAttribute.TypeFullName); return attr?.NamedArguments.FirstOrDefault(arg => arg.Key == "Type").Value.Value?.ToString() ?? "Full"; }

        public static string GetStringProp(AttributeMetadata attr, string key) =>
            attr != null && attr.Properties.TryGetValue(key, out var val) ? val?.ToString() ?? string.Empty : string.Empty;

        public static bool GetBoolProp(AttributeMetadata attr, string key, bool defaultValue)
        {
            if (attr != null && attr.Properties.TryGetValue(key, out var val))
                return val is bool b ? b : (val != null && val.ToString() != null && val.ToString().Equals("true", StringComparison.OrdinalIgnoreCase));
            return defaultValue;
        }


        /// <summary>
        /// 通过反射动态获取已知特性的属性默认值
        /// </summary>
        private Dictionary<string, object> GetAttributeDefaults(string typeFullName)
        {
            var defaults = new Dictionary<string, object>();
            if (string.IsNullOrEmpty(typeFullName)) return defaults;

            try
            {
                // 1. 获取 Abstractions 程序集 (因为所有特性都在这里)
                var assembly = typeof(DomainGenerateCodeAttribute).Assembly;

                // 2. 尝试从该程序集中获取对应的类型
                var targetType = assembly.GetType(typeFullName);

                // 3. 如果找到了该类型，且它确实是一个 Attribute
                if (targetType != null && typeof(Attribute).IsAssignableFrom(targetType))
                {
                    // 实例化特性类以触发其内部属性的默认值赋值
                    var instance = Activator.CreateInstance(targetType);

                    // 读取所有公共实例属性
                    foreach (var prop in targetType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
                    {
                        // 过滤掉内部/只写属性，以及系统自带的 TypeId 等
                        if (prop.CanRead && prop.Name != "TypeId")
                        {
                            defaults[prop.Name] = prop.GetValue(instance);
                        }
                    }
                }
            }
            catch
            {
                // 忽略实例化异常（例如抽象类、无无参构造函数的类或不在该程序集中的特性）
                // 安全降级为空字典
            }

            return defaults;
        }
        private string GetParamSummary(MethodDeclarationSyntax method, string name) { var trivia = method.GetLeadingTrivia().FirstOrDefault(t => t.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia)); if (trivia == default) return string.Empty; var xml = trivia.GetStructure() as DocumentationCommentTriviaSyntax; var param = xml?.Content.OfType<XmlElementSyntax>().FirstOrDefault(e => e.StartTag.Name.ToString().Equals("param", StringComparison.OrdinalIgnoreCase) && e.StartTag.Attributes.Any(a => a.ToString().Contains($"\"{name}\""))); return param != null ? CleanXmlText(param.Content.ToString()) : string.Empty; }

        private string CleanXmlText(string text)
        {
            return text.Replace("///", "").Replace("/**", "").Replace("*/", "").Replace("*", "").Trim();
        }

        #endregion    
    }
}