using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using xCodeGen.Abstractions.Extractors;
using xCodeGen.Abstractions.Metadata;

namespace xCodeGen.SourceGenerator
{
    public partial class CodeMetaDataExtractor
    {
        // 代码生成常量定义
        public const string GeneratedFileExtension = ".g.cs";
        public const string MetaFilePrefix = "Meta/";
        public const string DefaultTemplateName = "Default";
        public const string AutoGeneratedHeader = "// <auto-generated>\r\n// 自动生成代码，请勿手动修改\r\n// 生成器: CodeMetaDataExtractor\r\n// 生成时间: {0:o}\r\n// </auto-generated>\r\n\r\n";
        public const string DebugLogNamespace = "xCodeGen.DebugLogs";
        public const string DebugLogInterfaceName = "ICodeMetaDataExtractorLog";

        /// <summary>
        /// 异步提取元数据（源生成器环境中建议使用同步Extract方法，此方法仅为接口兼容）
        /// </summary>
        public Task<IEnumerable<RawMetadata>> ExtractAsync(ExtractorOptions options, CancellationToken cancellationToken = default)
        {
            // 源生成器环境下不推荐使用文件系统操作
            throw new NotImplementedException("源生成器环境建议使用同步Extract(Compilation)方法");
        }

        // 调试日志相关
        private readonly List<string> _DebugLogs = [];

        /// <summary>
        /// 记录调试日志
        /// </summary>
        protected void LogDebug(string message)
        {
            var log = $"[{DateTime.Now:HH:mm:ss.fff}] {message}";
            _DebugLogs.Add(log);
            System.Diagnostics.Debug.WriteLine($"[CodeMeta] {log}");
        }
    }
}