using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using xCodeGen.Abstractions.Attributes;
using xCodeGen.Abstractions.Metadata;

namespace xCodeGen.SourceGenerator
{
    public partial class CodeMetaDataExtractor
    {
        public const string GeneratedFileExtension = ".g.cs";
        public const string ProjectMetaContextName = "_ProjectMetaContext.g.cs";
        public const string MetaFilePrefix = "";//"Meta/";
        public const string InterfaceFilePrefix = "_Interfaces/";
        public const string DecoratorFilePrefix = "_Decorators/";
        public const string DefaultSubDomain = "";
        public const string AutoGeneratedHeader = @"// <auto-generated/>
// 自动生成代码，请勿手动修改
// 生成器: CodeMetaDataExtractor
// 生成时间: {0:yyyy-MM-dd HH:mm:ss}
#nullable enable
";

        #region --- Helper Functions ---

        public static string EscapeString(string value) => value?.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "").Replace("\n", "\\n") ?? string.Empty;

        public static string FormatStringValue(string value) => string.IsNullOrEmpty(value) ? "\"\"" : "@\"" + value.Replace("\"", "\"\"") + "\"";

        public static string GetLiteralValue(object value)
        {
            if (value == null) return "null";
            if (value is string s) return $"\"{EscapeString(s)}\"";
            if (value is bool b) return b.ToString().ToLower();
            if (value is int i) return i.ToString();
            if (value is long l) return l.ToString() + "L";
            if (value is Enum e) return $"{e.GetType().Name}.{e}";
            var strVal = value.ToString();
            return strVal.Contains("typeof(") ? strVal : $"\"{EscapeString(strVal)}\"";
        }

        public static string SanitizeFileName(string fileName) => string.IsNullOrEmpty(fileName) ? "Unknown" : new string(fileName.Select(c => System.IO.Path.GetInvalidFileNameChars().Contains(c) ? '_' : c).ToArray());

        public static string CleanXmlText(string text) => text.Replace("///", "").Replace("/**", "").Replace("*/", "").Replace("*", "").Trim();

        public static string TrimNamespace(string typeName)
        {
            if (string.IsNullOrEmpty(typeName)) return typeName;
            var lastDot = typeName.LastIndexOf('.');
            return lastDot >= 0 ? typeName.Substring(lastDot + 1) : typeName;
        }

        public static string GetGenericArgument(string typeName, int index = 0)
        {
            if (string.IsNullOrWhiteSpace(typeName) || !typeName.Contains("<")) return null;
            try
            {
                var start = typeName.IndexOf('<') + 1;
                var end = typeName.LastIndexOf('>');
                if (start <= 0 || end <= start) return null;

                var content = typeName.Substring(start, end - start);
                var arguments = new List<string>();
                var depth = 0;
                var lastPos = 0;

                for (var i = 0; i < content.Length; i++)
                {
                    if (content[i] == '<') depth++;
                    else if (content[i] == '>') depth--;
                    else if (content[i] == ',' && depth == 0)
                    {
                        arguments.Add(content.Substring(lastPos, i - lastPos).Trim());
                        lastPos = i + 1;
                    }
                }
                arguments.Add(content.Substring(lastPos).Trim());
                return (index >= 0 && index < arguments.Count) ? arguments[index] : null;
            }
            catch { return null; }
        }

        public static AttributeMetadata FindAttribute(IEnumerable<AttributeMetadata> attrs, string targetName) => attrs?.FirstOrDefault(a => !string.IsNullOrEmpty(a.TypeFullName) && a.TypeFullName.IndexOf(targetName, StringComparison.OrdinalIgnoreCase) >= 0);

        public static bool ImplementsInterface(ClassMetadata m, string interfaceName) => m.ImplementedInterfaces != null && m.ImplementedInterfaces.Any(i => !string.IsNullOrEmpty(i) && i.IndexOf(interfaceName, StringComparison.OrdinalIgnoreCase) >= 0);

        public static string GetGenerateMode(INamedTypeSymbol symbol)
        {
            var attr = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == DomainGenerateCodeAttribute.TypeFullName);
            return attr?.NamedArguments.FirstOrDefault(arg => arg.Key == "Type").Value.Value?.ToString() ?? "Full";
        }

        public static string GetStringProp(AttributeMetadata attr, string key) => attr != null && attr.Properties.TryGetValue(key, out var val) ? val?.ToString() ?? string.Empty : string.Empty;

        public static bool GetBoolProp(AttributeMetadata attr, string key, bool defaultValue)
        {
            if (attr != null && attr.Properties.TryGetValue(key, out var val))
                return val is bool b ? b : (val != null && val.ToString().Equals("true", StringComparison.OrdinalIgnoreCase));
            return defaultValue;
        }

        public static Dictionary<string, object> GetAttributeDefaults(string typeFullName)
        {
            var defaults = new Dictionary<string, object>();
            if (string.IsNullOrEmpty(typeFullName)) return defaults;
            try
            {
                var assembly = typeof(DomainGenerateCodeAttribute).Assembly;
                var targetType = assembly.GetType(typeFullName);
                if (targetType != null && typeof(Attribute).IsAssignableFrom(targetType))
                {
                    var instance = Activator.CreateInstance(targetType);
                    foreach (var prop in targetType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
                    {
                        if (prop.CanRead && prop.Name != "TypeId") defaults[prop.Name] = prop.GetValue(instance);
                    }
                }
            }
            catch { }
            return defaults;
        }

        public static string FormatAttributeForCode(AttributeMetadata attr)
        {
            var args = new List<string>();
            if (attr.ConstructorArguments != null) args.AddRange(attr.ConstructorArguments.Select(GetLiteralValue));
            if (attr.Properties != null)
            {
                foreach (var kv in attr.Properties)
                {
                    // 核心修复 1：过滤掉内部用于标记的 IsDomainFilter，不输出到生成的接口
                    if (kv.Key == "IsDomainFilter") continue;
                    args.Add($"{kv.Key} = {GetLiteralValue(kv.Value)}");
                }
            }
            var attrContent = args.Count > 0 ? $"({string.Join(", ", args)})" : "";
            // 核心修复 2：统一使用短名称，去掉结尾的 Attribute 后缀使代码更干净
            var shortName = attr.Name.EndsWith("Attribute") ? attr.Name.Substring(0, attr.Name.Length - 9) : attr.Name;
            return $"[{shortName}{attrContent}]";
        }

        public static string GetParamSummary(MethodDeclarationSyntax method, string name)
        {
            var trivia = method.GetLeadingTrivia().FirstOrDefault(t => t.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia));
            if (trivia == default) return string.Empty;
            var xml = trivia.GetStructure() as DocumentationCommentTriviaSyntax;
            var param = xml?.Content.OfType<XmlElementSyntax>().FirstOrDefault(e => e.StartTag.Name.ToString().Equals("param", StringComparison.OrdinalIgnoreCase) && e.StartTag.Attributes.Any(a => a.ToString().Contains($"\"{name}\"")));
            return param != null ? CleanXmlText(param.Content.ToString()) : string.Empty;
        }

        #endregion
    }
}