using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using xCodeGen.Abstractions.Metadata;
// ReSharper disable ConvertTypeCheckPatternToNullCheck

namespace xCodeGen.SourceGenerator
{
    public partial class CodeMetaDataExtractor
    {
        public void GenerateMetaFile(SourceProductionContext context, ClassMetadata metadata)
        {
            try
            {
                var sanitizedClassName = SanitizeFileName(metadata.ClassName);
                var fileName = $"{MetaFilePrefix}{sanitizedClassName}Meta{GeneratedFileExtension}";
                var codeContent = BuildMetaCode(metadata);
                context.AddSource(fileName, SourceText.From(codeContent, Encoding.UTF8));
            }
            catch (Exception ex) { ReportError(context, $"生成元数据时出错: {ex.Message}"); }
        }

        private string BuildMetaCode(ClassMetadata metadata)
        {
            var codeBuilder = new StringBuilder();
            codeBuilder.AppendFormat(AutoGeneratedHeader, DateTime.UtcNow);

            codeBuilder.AppendLine("using System;");
            codeBuilder.AppendLine("using System.Collections.Generic;");
            codeBuilder.AppendLine("using System.Collections.ObjectModel;");
            codeBuilder.AppendLine("using xCodeGen.Abstractions.Metadata;");
            codeBuilder.AppendLine();
            codeBuilder.AppendLine($"namespace {metadata.Namespace}.Generated");
            codeBuilder.AppendLine("{");
            codeBuilder.AppendLine($"    public class {metadata.ClassName}Meta");
            codeBuilder.AppendLine("    {");
            codeBuilder.AppendLine("        public static ClassMetadata Metadata { get; } = new ClassMetadata");
            codeBuilder.AppendLine("        {");
            codeBuilder.AppendLine($"            Namespace = \"{EscapeString(metadata.Namespace)}\",");
            codeBuilder.AppendLine($"            ClassName = \"{EscapeString(metadata.ClassName)}\",");
            codeBuilder.AppendLine($"            FullName = \"{EscapeString(metadata.FullName)}\",");
            codeBuilder.AppendLine($"            Type = MetaType.{metadata.Type},");
            codeBuilder.AppendLine($"            Summary = {FormatStringValue(metadata.Summary)},");
            codeBuilder.AppendLine($"            IsRecord = {metadata.IsRecord.ToString().ToLower()},");
            codeBuilder.AppendLine($"            TypeKind = \"{EscapeString(metadata.TypeKind)}\",");
            codeBuilder.AppendLine($"            BaseType = \"{EscapeString(metadata.BaseType)}\",");
            codeBuilder.AppendLine($"            DecoratorTypeFullName = {(string.IsNullOrEmpty(metadata.DecoratorTypeFullName) ? "null" : $"\"{EscapeString(metadata.DecoratorTypeFullName)}\"")},");
            codeBuilder.AppendLine($"            HasDecoratorCandidate = {metadata.HasDecoratorCandidate.ToString().ToLower()},");
            codeBuilder.AppendLine($"            SourceHash = \"{EscapeString(metadata.SourceHash)}\",");

            codeBuilder.AppendLine("            Attributes = new Collection<AttributeMetadata>");
            codeBuilder.AppendLine("            {");
            if (metadata.Attributes != null)
            {
                foreach (var attr in metadata.Attributes) BuildAttributeInitialization(codeBuilder, attr, "                ");
            }
            codeBuilder.AppendLine("            },");

            codeBuilder.AppendLine("            Properties = new Collection<PropertyMetadata>");
            codeBuilder.AppendLine("            {");
            foreach (var prop in metadata.Properties)
            {
                codeBuilder.AppendLine("                new PropertyMetadata");
                codeBuilder.AppendLine("                {");
                codeBuilder.AppendLine($"                    Name = \"{EscapeString(prop.Name)}\",");
                codeBuilder.AppendLine($"                    TypeName = \"{EscapeString(prop.TypeName)}\",");
                codeBuilder.AppendLine($"                    TypeFullName = \"{EscapeString(prop.TypeFullName)}\",");
                codeBuilder.AppendLine($"                    IsNullable = {prop.IsNullable.ToString().ToLower()},");
                codeBuilder.AppendLine($"                    Summary = {FormatStringValue(prop.Summary)},");
                // 修复：生成 List 防止集合隐式转换异常
                codeBuilder.AppendLine("                    Attributes = new List<AttributeMetadata>");
                codeBuilder.AppendLine("                    {");
                foreach (var attr in prop.Attributes) BuildAttributeInitialization(codeBuilder, attr, "                        ");
                codeBuilder.AppendLine("                    }");
                codeBuilder.AppendLine("                },");
            }
            codeBuilder.AppendLine("            },");

            codeBuilder.AppendLine("            Methods = new Collection<MethodMetadata>");
            codeBuilder.AppendLine("            {");
            foreach (var method in metadata.Methods)
            {
                codeBuilder.AppendLine("                new MethodMetadata");
                codeBuilder.AppendLine("                {");
                codeBuilder.AppendLine($"                    Name = \"{EscapeString(method.Name)}\",");
                codeBuilder.AppendLine($"                    ReturnType = \"{EscapeString(method.ReturnType)}\",");
                codeBuilder.AppendLine($"                    IsAsync = {method.IsAsync.ToString().ToLower()},");
                codeBuilder.AppendLine($"                    Summary = {FormatStringValue(method.Summary)},");
                // --- 核心补充：输出定性标签与物理文件 ---
                codeBuilder.AppendLine($"                    Origin = MethodOrigin.{method.Origin},");
                codeBuilder.AppendLine($"                    SourceFile = \"{EscapeString(method.SourceFile)}\",");

                codeBuilder.AppendLine($"                    AccessModifier = \"{EscapeString(method.AccessModifier)}\",");
                codeBuilder.AppendLine("                    Parameters = new List<ParameterMetadata>");
                codeBuilder.AppendLine("                    {");
                foreach (var param in method.Parameters)
                {
                    codeBuilder.AppendLine($"                        new ParameterMetadata {{ Name = \"{EscapeString(param.Name)}\", TypeName = \"{EscapeString(param.TypeName)}\", IsNullable = {param.IsNullable.ToString().ToLower()}, Summary = {FormatStringValue(param.Summary)} }},");
                }
                codeBuilder.AppendLine("                    },");
                // 修复：生成 List 防止集合隐式转换异常
                codeBuilder.AppendLine("                    Attributes = new List<AttributeMetadata>");
                codeBuilder.AppendLine("                    {");
                if (method is MethodMetadata mm && mm.Attributes != null)
                {
                    foreach (var attr in mm.Attributes) BuildAttributeInitialization(codeBuilder, attr, "                        ");
                }
                codeBuilder.AppendLine("                    }");
                codeBuilder.AppendLine("                },");
            }
            codeBuilder.AppendLine("            }");
            codeBuilder.AppendLine("        };");
            codeBuilder.AppendLine("    }");
            codeBuilder.AppendLine("}");
            return codeBuilder.ToString();
        }

        private void BuildAttributeInitialization(StringBuilder codeBuilder, AttributeMetadata attr, string indent)
        {
            codeBuilder.AppendLine($"{indent}new AttributeMetadata");
            codeBuilder.AppendLine($"{indent}{{");
            codeBuilder.AppendLine($"{indent}    Name = \"{EscapeString(attr.Name)}\",");
            codeBuilder.AppendLine($"{indent}    TypeFullName = \"{EscapeString(attr.TypeFullName)}\",");

            codeBuilder.AppendLine($"{indent}    ConstructorArguments = new Collection<object>");
            codeBuilder.AppendLine($"{indent}    {{");
            foreach (var arg in attr.ConstructorArguments) codeBuilder.AppendLine($"{indent}        {GetLiteralValue(arg)},");
            codeBuilder.AppendLine($"{indent}    }},");

            codeBuilder.AppendLine($"{indent}    Properties = new Dictionary<string, object>");
            codeBuilder.AppendLine($"{indent}    {{");
            foreach (var prop in attr.Properties) codeBuilder.AppendLine($"{indent}        {{ \"{EscapeString(prop.Key)}\", {GetLiteralValue(prop.Value)} }},");
            codeBuilder.AppendLine($"{indent}    }},");
            codeBuilder.AppendLine($"{indent}}},");
        }

        public void GenerateProjectMetaContext(SourceProductionContext context, ClassMetadata[] allMetadatas, ProjectInfo projectInfo, MetadataChangeLog changeLog)
        {
            var entities = allMetadatas.Where(m => m.Type == MetaType.Entity);
            try
            {
                var codeBuilder = new StringBuilder();
                codeBuilder.AppendLine("// <auto-generated/>");
                codeBuilder.AppendLine("#nullable enable");
                codeBuilder.AppendLine("using System;");
                codeBuilder.AppendLine("using System.Collections.Generic;");
                codeBuilder.AppendLine("using System.Linq;");
                codeBuilder.AppendLine("using xCodeGen.Abstractions.Metadata;");
                codeBuilder.AppendLine();
                codeBuilder.AppendLine($"namespace {projectInfo.GeneratedNamespace}");
                codeBuilder.AppendLine("{");
                codeBuilder.AppendLine("    public class ProjectMetaContext : ProjectMetaContextBase");
                codeBuilder.AppendLine("    {");
                codeBuilder.AppendLine("        static ProjectMetaContext()");
                codeBuilder.AppendLine("        {");
                codeBuilder.AppendLine("            Instance = new ProjectMetaContext();");
                codeBuilder.AppendLine("        }");
                codeBuilder.AppendLine();
                codeBuilder.AppendLine("        private ProjectMetaContext()");
                codeBuilder.AppendLine("        {");
                foreach (var metadata in entities.OrderBy(m => m.ClassName))
                    codeBuilder.AppendLine($"            _allMetadatas.Add({metadata.Namespace}.Generated.{metadata.ClassName}Meta.Metadata);");
                codeBuilder.AppendLine("        }");
                codeBuilder.AppendLine();
                codeBuilder.AppendLine($"        public override ProjectConfiguration Configuration {{ get; }} = new ProjectConfiguration(projectDirectory: \"{EscapeString(projectInfo.ProjectDirectory)}\", outputPath: \"{EscapeString(projectInfo.OutputPath)}\", rootNamespace: \"{EscapeString(projectInfo.RootNamespace)}\", assemblyName: \"{EscapeString(projectInfo.AssemblyName)}\", targetFramework: \"{EscapeString(projectInfo.TargetFramework)}\", buildConfiguration: \"{EscapeString(projectInfo.BuildConfiguration)}\", langVersion: \"{EscapeString(projectInfo.LangVersion)}\", nullable: \"{EscapeString(projectInfo.Nullable)}\", generatedNamespace: \"{EscapeString(projectInfo.GeneratedNamespace)}\", generatedFilesDirectory: \"{EscapeString(projectInfo.GeneratedFilesDirectory)}\", generatorVersion: \"{EscapeString(projectInfo.GeneratorVersion)}\");");
                codeBuilder.AppendLine("        public override MetadataChangeLog ChangeLog { get; } = new MetadataChangeLog();");
                codeBuilder.AppendLine("        public override string MetadataSchemaVersion => \"2.4\";");
                codeBuilder.AppendLine();

                var services = allMetadatas.Where(m => m.Type == MetaType.Service || m.Type == MetaType.DataService || m.Type == MetaType.Controller).ToArray();
                BuildRegistrationMethod(codeBuilder, services);

                codeBuilder.AppendLine("    }");
                codeBuilder.AppendLine("}");
                context.AddSource("ProjectMetaContext.g.cs", SourceText.From(codeBuilder.ToString(), Encoding.UTF8));
            }
            catch (Exception ex) { ReportError(context, $"生成 ProjectMetaContext 失败: {ex.Message}"); }
        }

        private void BuildRegistrationMethod(StringBuilder sb, ClassMetadata[] services)
        {
            sb.AppendLine("        /// <summary> 获取所有领域服务注册映射 </summary>");
            sb.AppendLine("        public override IEnumerable<DomainServiceRegistration> GetServiceRegistrations()");
            sb.AppendLine("        {");

            if (services.Length == 0)
            {
                sb.AppendLine("            yield break;");
            }
            else
            {
                sb.AppendLine("           // Services");
                foreach (var m in services.Where(s => s.Type == MetaType.Service)) WriteContent(m);
                sb.AppendLine("           // Data Services");
                foreach (var m in services.Where(s => s.Type == MetaType.DataService)) WriteContent(m);
                sb.AppendLine("           // Controllers");
                foreach (var m in services.Where(s => s.Type == MetaType.Controller)) WriteContent(m);
            }
            sb.AppendLine("        }");

            void WriteContent(ClassMetadata m)
            {
                var interfaceFullName = m.Interface?.FullName ?? m.InterfaceName;
                var decoratorName = m.HasDecoratorCandidate ? $"typeof(global::{m.DecoratorTypeFullName})" : $"typeof(global::{m.Namespace}.Generated.{m.ClassName}Decorator)";
                var proxyExpr = m.Type == MetaType.Controller && m.HasDecoratorCandidate ? decoratorName : "null";
                var interfaceParameter = m.Type == MetaType.Controller && interfaceFullName != null ? $"typeof(global::{interfaceFullName})" : "null";
                sb.AppendLine($@"            yield return new DomainServiceRegistration(
                {interfaceParameter}, 
                typeof(global::{m.FullName}), 
                {proxyExpr}, 
                MetaType.{m.Type});");
            }
        }

        public void GenerateDecoratorFile(SourceProductionContext context, ClassMetadata controller)
        {
            if (controller == null || controller.Type != MetaType.Controller) return;

            var userType = string.IsNullOrEmpty(controller.UserType) ? "object" : controller.UserType;
            var controllerName = controller.ClassName;
            var interfaceName = $"I{controllerName}";
            var decoratorNamespace = $"{controller.Namespace}.Generated";
            var decoratorClassName = $"{controllerName}Decorator";
            var fullDecoratorName = $"{decoratorNamespace}.{decoratorClassName}";
            var accessibility = controller.Accessibility;
            var sb = new StringBuilder();
            sb.AppendFormat(AutoGeneratedHeader, DateTime.UtcNow);

            // 核心功能：汇聚固定 using 和来自源控制器提取的 using
            var usings = new HashSet<string>
            {
                "using System;",
                "using System.Threading.Tasks;",
                "using TKW.Framework.Domain;",
                "using TKW.Framework.Domain.Interfaces;",
                "using TKW.Framework.Domain.Interception;",
                $"using {controller.Namespace};"
            };

            if (controller.GenerateCodeSettings.TryGetValue("Usings", out var uObj) && uObj is List<string> controllerUsings)
            {
                foreach (var u in controllerUsings) usings.Add(u.Trim());
            }

            foreach (var u in usings) sb.AppendLine(u);

            sb.AppendLine();
            sb.AppendLine($"namespace {decoratorNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    {accessibility} class {decoratorClassName}");
            sb.AppendLine($"        : DomainControllerDecoratorBase<{controllerName}, {userType}>, {interfaceName}, IGeneratedByxCodeGenSG");
            sb.AppendLine("    {");
            sb.AppendLine($"        private readonly {controllerName} _realService;");
            sb.AppendLine($"        private readonly StaticDomainInterceptor<{userType}> _interceptor;");
            sb.AppendLine();
            sb.AppendLine($"        {accessibility} {decoratorClassName}({controllerName} realService, StaticDomainInterceptor<{userType}> interceptor) : base(realService, interceptor)");
            sb.AppendLine("        {");
            sb.AppendLine("            _realService = realService;");
            sb.AppendLine("            _interceptor = interceptor;");
            sb.AppendLine("        }");

            foreach (var method in controller.Methods)
            {
                // 现在能正确拦截了，因为前面兜底策略找到了 Filter
                var hasFilter = method.Attributes.Any(a => GetBoolProp(a, "IsDomainFilter", false));

                // 移除 Replace 暴力替换，类型已经是短名称 (如 Task<DmpUserInfo>)
                var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
                var argList = string.Join(", ", method.Parameters.Select(p => p.Name));

                var isVoid = method.ReturnType == "void";
                var isGenericTask = method.ReturnType.Contains("Task<");
                var isPlainTask = method.ReturnType == "Task";

                var isAsync = isPlainTask || isGenericTask || method.IsAsync;
                var hasReturnValue = !isVoid && !isPlainTask;

                var actualReturnType = method.ReturnType;
                if (isGenericTask)
                {
                    var start = actualReturnType.IndexOf('<') + 1;
                    var length = actualReturnType.LastIndexOf('>') - start;
                    if (start > 0 && length > 0) actualReturnType = actualReturnType.Substring(start, length);
                }

                sb.AppendLine();
                sb.AppendLine($"        public {(isAsync ? "async " : "")}{method.ReturnType} {method.Name}({paramList})");
                sb.AppendLine("        {");

                if (hasFilter)
                {
                    sb.AppendLine($"            var context = new InvocationContext(this, _realService, \"{method.Name}\", new object[] {{ {argList} }});");
                    if (isAsync)
                    {
                        sb.AppendLine("            await _interceptor.InterceptAsync(context, async () => {");
                        sb.AppendLine($"                {(hasReturnValue ? "context.ReturnValue = " : "")}await _realService.{method.Name}({argList});");
                        sb.AppendLine("            });");
                        if (hasReturnValue) sb.AppendLine($"            return (context.ReturnValue is null) ? default : ({actualReturnType})context.ReturnValue;");
                    }
                    else
                    {
                        sb.AppendLine("            _interceptor.InterceptAsync(context, () => {");
                        sb.AppendLine($"                {(hasReturnValue ? "context.ReturnValue = " : "")}_realService.{method.Name}({argList});");
                        sb.AppendLine("                return Task.CompletedTask;");
                        sb.AppendLine("            }).GetAwaiter().GetResult();");
                        if (hasReturnValue) sb.AppendLine($"            return (context.ReturnValue is null) ? default : ({actualReturnType})context.ReturnValue;");
                    }
                }
                else
                {
                    var awaitStr = isAsync ? "await " : "";
                    var returnStr = hasReturnValue ? "return " : "";
                    sb.AppendLine($"            {returnStr}{awaitStr}_realService.{method.Name}({argList});");
                }
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            context.AddSource($"{DecoratorFilePrefix}{decoratorClassName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            // 同步装饰器状态，触发 ProjectMetaContext 中的代理注册
            controller.HasDecoratorCandidate = true;
            controller.DecoratorTypeFullName = fullDecoratorName;
        }

        public void GenerateInterfaceFile(SourceProductionContext context, ClassMetadata controller)
        {
            if (controller == null || controller.Type != MetaType.Controller) return;

            var interfaceName = $"I{controller.ClassName}";
            var interfaceNamespace = controller.Namespace;

            var sb = new StringBuilder();
            sb.AppendFormat(AutoGeneratedHeader, DateTime.UtcNow);

            // 加入 Usings
            var usings = new HashSet<string>
            {
                "using System;",
                "using System.Collections.Generic;",
                "using System.Threading.Tasks;",
                "using TKW.Framework.Domain.Interfaces;"
            };

            if (controller.GenerateCodeSettings.TryGetValue("Usings", out var uObj) && uObj is List<string> controllerUsings)
            {
                foreach (var u in controllerUsings) usings.Add(u.Trim());
            }

            foreach (var u in usings) sb.AppendLine(u);

            sb.AppendLine();
            sb.AppendLine($"namespace {interfaceNamespace};");
            sb.AppendLine();
            sb.AppendLine($"public partial interface {interfaceName} : IAopContract, IGeneratedByxCodeGenSG");
            sb.AppendLine("{");

            foreach (var method in controller.Methods)
            {
                //sb.AppendLine($"    ///<summary>{method.Summary}</summary>");
                if (method.Attributes != null)
                {
                    // 统一使用过滤完内部属性并去除了 global:: 和长后缀的 FormatAttributeForCode
                    foreach (var attr in method.Attributes) sb.AppendLine($"    {FormatAttributeForCode(attr)}");
                }
                var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
                sb.AppendLine($"    {method.ReturnType} {method.Name}({paramList});");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            context.AddSource($"{InterfaceFilePrefix}{interfaceName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            // 更新元数据关联，以便 ProjectMetaContext 注册时使用
            controller.Interface = new ClassMetadata
            {
                ClassName = interfaceName,
                Namespace = interfaceNamespace,
                FullName = $"{interfaceNamespace}.{interfaceName}",
                Type = MetaType.Interface
            };
            controller.InterfaceName = interfaceName;
        }

        private void ReportError(SourceProductionContext context, string message)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("CMD001", "元数据生成错误", message, "CodeMeta", DiagnosticSeverity.Error, true),
                Location.None));
        }
    }
}