using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using xCodeGen.Abstractions.Metadata;
using System.Security.Cryptography;

namespace xCodeGen.SourceGenerator
{
    public partial class CodeMetaDataExtractor
    {
        public void GenerateMetaFile(SourceProductionContext context, ClassMetadata metadata)
        {
            try
            {
                var sanitizedClassName = SanitizeFileName(metadata.ClassName);
                var fileName = $"{MetaFilePrefix}{sanitizedClassName}Meta{GeneratedFileExtension}";
                var codeContent = BuildMetaCode(metadata);
                context.AddSource(fileName, SourceText.From(codeContent, Encoding.UTF8));
            }
            catch (Exception ex) { ReportError(context, $"生成元数据时出错: {ex.Message}"); }
        }

        private string BuildMetaCode(ClassMetadata metadata)
        {
            var codeBuilder = new StringBuilder();
            codeBuilder.AppendFormat(AutoGeneratedHeader, DateTime.UtcNow);

            codeBuilder.AppendLine("using System;");
            codeBuilder.AppendLine("using System.Collections.Generic;");
            codeBuilder.AppendLine("using System.Collections.ObjectModel;");
            codeBuilder.AppendLine("using xCodeGen.Abstractions.Metadata;");
            codeBuilder.AppendLine();
            codeBuilder.AppendLine($"namespace {metadata.Namespace}.Generated");
            codeBuilder.AppendLine("{");
            codeBuilder.AppendLine($"    public class {metadata.ClassName}Meta");
            codeBuilder.AppendLine("    {");
            codeBuilder.AppendLine("        public static ClassMetadata Metadata { get; } = new ClassMetadata");
            codeBuilder.AppendLine("        {");
            codeBuilder.AppendLine($"            Namespace = \"{EscapeString(metadata.Namespace)}\",");
            codeBuilder.AppendLine($"            ClassName = \"{EscapeString(metadata.ClassName)}\",");
            codeBuilder.AppendLine($"            FullName = \"{EscapeString(metadata.FullName)}\",");
            codeBuilder.AppendLine($"            Type = MetaType.{metadata.Type},"); // 核心：使用统一的 Type 属性
            codeBuilder.AppendLine($"            Summary = {FormatStringValue(metadata.Summary)},");
            codeBuilder.AppendLine($"            IsRecord = {metadata.IsRecord.ToString().ToLower()},");
            codeBuilder.AppendLine($"            TypeKind = \"{EscapeString(metadata.TypeKind)}\",");
            codeBuilder.AppendLine($"            BaseType = \"{EscapeString(metadata.BaseType)}\",");

            // 记录装饰器关联信息
            codeBuilder.AppendLine($"            DecoratorTypeFullName = {(string.IsNullOrEmpty(metadata.DecoratorTypeFullName) ? "null" : $"\"{EscapeString(metadata.DecoratorTypeFullName)}\"")},");
            codeBuilder.AppendLine($"            HasDecoratorCandidate = {metadata.HasDecoratorCandidate.ToString().ToLower()},");
            codeBuilder.AppendLine($"            SourceHash = \"{EscapeString(metadata.SourceHash)}\",");
            
            // --- 序列化 Class 级别的 Attributes ---
            codeBuilder.AppendLine("            Attributes = new Collection<AttributeMetadata>");
            codeBuilder.AppendLine("            {");
            if (metadata.Attributes != null)
            {
                foreach (var attr in metadata.Attributes)
                {
                    BuildAttributeInitialization(codeBuilder, attr, "                ");
                }
            }
            codeBuilder.AppendLine("            },");

            // Properties
            codeBuilder.AppendLine("            Properties = new Collection<PropertyMetadata>");
            codeBuilder.AppendLine("            {");
            foreach (var prop in metadata.Properties)
            {
                codeBuilder.AppendLine("                new PropertyMetadata");
                codeBuilder.AppendLine("                {");
                codeBuilder.AppendLine($"                    Name = \"{EscapeString(prop.Name)}\",");
                codeBuilder.AppendLine($"                    TypeName = \"{EscapeString(prop.TypeName)}\",");
                codeBuilder.AppendLine($"                    TypeFullName = \"{EscapeString(prop.TypeFullName)}\",");
                codeBuilder.AppendLine($"                    IsNullable = {prop.IsNullable.ToString().ToLower()},");
                codeBuilder.AppendLine($"                    Summary = {FormatStringValue(prop.Summary)},");
                codeBuilder.AppendLine("                    Attributes = new List<AttributeMetadata>");
                codeBuilder.AppendLine("                    {");
                foreach (var attr in prop.Attributes)
                {
                    BuildAttributeInitialization(codeBuilder, attr, "                        ");
                }
                codeBuilder.AppendLine("                    }");
                codeBuilder.AppendLine("                },");
            }
            codeBuilder.AppendLine("            },");

            // Methods (包括方法级 Attributes)
            codeBuilder.AppendLine("            Methods = new Collection<MethodMetadata>");
            codeBuilder.AppendLine("            {");
            foreach (var method in metadata.Methods)
            {
                codeBuilder.AppendLine("                new MethodMetadata");
                codeBuilder.AppendLine("                {");
                codeBuilder.AppendLine($"                    Name = \"{EscapeString(method.Name)}\",");
                codeBuilder.AppendLine($"                    ReturnType = \"{EscapeString(method.ReturnType)}\",");
                codeBuilder.AppendLine($"                    IsAsync = {method.IsAsync.ToString().ToLower()},");
                codeBuilder.AppendLine($"                    Summary = {FormatStringValue(method.Summary)},");
                codeBuilder.AppendLine($"                    AccessModifier = \"{EscapeString(method.AccessModifier)}\",");
                codeBuilder.AppendLine("                    Parameters = new List<ParameterMetadata>");
                codeBuilder.AppendLine("                    {");
                foreach (var param in method.Parameters)
                {
                    codeBuilder.AppendLine($"                        new ParameterMetadata {{ Name = \"{EscapeString(param.Name)}\", TypeName = \"{EscapeString(param.TypeName)}\", IsNullable = {param.IsNullable.ToString().ToLower()}, Summary = {FormatStringValue(param.Summary)} }},");
                }
                codeBuilder.AppendLine("                    },");
                // 方法级 Attributes（如果有）
                codeBuilder.AppendLine("                    Attributes = new Collection<AttributeMetadata>");
                codeBuilder.AppendLine("                    {");
                if (method is MethodMetadata mm && mm.Attributes != null)
                {
                    foreach (var attr in mm.Attributes)
                    {
                        BuildAttributeInitialization(codeBuilder, attr, "                        ");
                    }
                }
                codeBuilder.AppendLine("                    }");
                codeBuilder.AppendLine("                },");
            }
            codeBuilder.AppendLine("            }");
            codeBuilder.AppendLine("        };");
            codeBuilder.AppendLine("    }");
            codeBuilder.AppendLine("}");

            return codeBuilder.ToString();
        }

        /// <summary>
        /// 内部辅助：构建 AttributeMetadata 的 C# 初始化代码
        /// </summary>
        private void BuildAttributeInitialization(StringBuilder codeBuilder, AttributeMetadata attr, string indent)
        {
            codeBuilder.AppendLine($"{indent}new AttributeMetadata");
            codeBuilder.AppendLine($"{indent}{{");
            codeBuilder.AppendLine($"{indent}    Name = \"{EscapeString(attr.Name)}\",");
            codeBuilder.AppendLine($"{indent}    TypeFullName = \"{EscapeString(attr.TypeFullName)}\",");

            // 序列化构造函数参数
            codeBuilder.AppendLine($"{indent}    ConstructorArguments = new Collection<object>");
            codeBuilder.AppendLine($"{indent}    {{");
            foreach (var arg in attr.ConstructorArguments)
            {
                codeBuilder.AppendLine($"{indent}        {GetLiteralValue(arg)},");
            }

            codeBuilder.AppendLine($"{indent}    }},");

            // 序列化命名参数字典 (Properties & NamedArguments)
            codeBuilder.AppendLine($"{indent}    Properties = new Dictionary<string, object>");
            codeBuilder.AppendLine($"{indent}    {{");
            foreach (var prop in attr.Properties)
            {
                codeBuilder.AppendLine(
                    $"{indent}        {{ \"{EscapeString(prop.Key)}\", {GetLiteralValue(prop.Value)} }},");
            }

            codeBuilder.AppendLine($"{indent}    }},");

            codeBuilder.AppendLine($"{indent}}},");
        }

        public void GenerateProjectMetaContext(SourceProductionContext context, IEnumerable<ClassMetadata> allMetadatas, ProjectInfo projectInfo, MetadataChangeLog changeLog)
        {
            var classMetadatas = allMetadatas.ToList();

            try
            {
                var codeBuilder = new StringBuilder();
                codeBuilder.AppendLine("// <auto-generated/>");
                codeBuilder.AppendLine("#nullable disable");
                codeBuilder.AppendLine("using System;");
                codeBuilder.AppendLine("using System.Collections.Generic;");
                codeBuilder.AppendLine("using System.Linq;");
                codeBuilder.AppendLine("using xCodeGen.Abstractions.Metadata;");
                codeBuilder.AppendLine();
                codeBuilder.AppendLine($"namespace {projectInfo.GeneratedNamespace}");
                codeBuilder.AppendLine("{");

                codeBuilder.AppendLine("    public class ProjectMetaContext : ProjectMetaContextBase");
                codeBuilder.AppendLine("    {");

                codeBuilder.AppendLine("        static ProjectMetaContext()");
                codeBuilder.AppendLine("        {");
                codeBuilder.AppendLine("            Instance = new ProjectMetaContext();");
                codeBuilder.AppendLine("        }");
                codeBuilder.AppendLine();
                codeBuilder.AppendLine("        private ProjectMetaContext()");
                codeBuilder.AppendLine("        {");
                foreach (var metadata in classMetadatas.OrderBy(m => m.ClassName))
                    codeBuilder.AppendLine($"            _allMetadatas.Add({metadata.Namespace}.Generated.{metadata.ClassName}Meta.Metadata);");
                codeBuilder.AppendLine("        }");
                codeBuilder.AppendLine();

                codeBuilder.AppendLine($"        public override ProjectConfiguration Configuration {{ get; }} = new ProjectConfiguration(projectDirectory: \"{EscapeString(projectInfo.ProjectDirectory)}\", outputPath: \"{EscapeString(projectInfo.OutputPath)}\", rootNamespace: \"{EscapeString(projectInfo.RootNamespace)}\", assemblyName: \"{EscapeString(projectInfo.AssemblyName)}\", targetFramework: \"{EscapeString(projectInfo.TargetFramework)}\", buildConfiguration: \"{EscapeString(projectInfo.BuildConfiguration)}\", langVersion: \"{EscapeString(projectInfo.LangVersion)}\", nullable: \"{EscapeString(projectInfo.Nullable)}\", generatedNamespace: \"{EscapeString(projectInfo.GeneratedNamespace)}\", generatedFilesDirectory: \"{EscapeString(projectInfo.GeneratedFilesDirectory)}\", generatorVersion: \"{EscapeString(projectInfo.GeneratorVersion)}\");");
                codeBuilder.AppendLine("        public override MetadataChangeLog ChangeLog { get; } = new MetadataChangeLog();");
                codeBuilder.AppendLine("        public override string MetadataSchemaVersion => \"2.1\";");
                codeBuilder.AppendLine();

                codeBuilder.AppendLine("    }");
                codeBuilder.AppendLine("}");

                context.AddSource("ProjectMetaContext.g.cs", SourceText.From(codeBuilder.ToString(), Encoding.UTF8));
            }
            catch (Exception ex) { ReportError(context, $"生成 ProjectMetaContext 失败: {ex.Message}"); }
        }

        private void GenerateDebugLogFile(SourceProductionContext context)
        {
            var logContent = new StringBuilder();
            logContent.AppendLine("namespace " + DebugLogNamespace +
                                  " { public class CodeMetaData_DebugLog { public static List<string> Logs = new List<string>(); } }");
            context.AddSource("Logs/CodeMetaData_DebugLog.g.cs", SourceText.From(logContent.ToString(), Encoding.UTF8));
        }

        private void ReportError(SourceProductionContext context, string message)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("CMD001", "元数据生成错��", message, "CodeMeta", DiagnosticSeverity.Error, true),
                Location.None));
        }

        private string EscapeString(string value)
        {
            if (value == null) return string.Empty;
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "").Replace("\n", "\\n");
        }

        private string FormatStringValue(string value)
        {
            if (string.IsNullOrEmpty(value)) return "\"\"";
            return "@\"" + value.Replace("\"", "\"\"") + "\"";
        }

        /// <summary>
        /// 获取值的字面量表示，确保类型安全
        /// </summary>
        private string GetLiteralValue(object value)
        {
            if (value == null) return "null";
            if (value is string s) return $"\"{EscapeString(s)}\"";
            if (value is bool b) return b.ToString().ToLower();
            if (value is int i) return i.ToString();
            if (value is long l) return l.ToString() + "L";
            if (value is Enum e) return $"{e.GetType().Name}.{e}";

            // 处理 typeof() 情况
            var strVal = value.ToString();
            if (strVal.Contains("typeof(")) return strVal;

            return $"\"{EscapeString(strVal)}\""; // 默认作为字符串回退，防止生成非法代码
        }

        private string SanitizeFileName(string fileName) => string.IsNullOrEmpty(fileName)
            ? "Unknown"
            : new string(fileName.Select(c => System.IO.Path.GetInvalidFileNameChars().Contains(c) ? '_' : c)
                .ToArray());

        private void EnrichAndHashMetadatas(ref List<ClassMetadata> allMetadatas)
        {
            if (allMetadatas == null || allMetadatas.Count == 0) return;

            var filteredList = new List<ClassMetadata>();

            // --- 第一步：身份判定与 Type 归类 ---
            foreach (var m in allMetadatas)
            {
                // 1. GenerateCode 特性优先判定 View/Entity
                var genCodeAttr = FindAttribute(m.Attributes, "GenerateCodeAttribute");
                if (genCodeAttr != null)
                {
                    var isView = GetBoolProp(genCodeAttr, "IsView", false);
                    m.Type = isView ? MetaType.View : MetaType.Entity;
                    filteredList.Add(m);
                    continue;
                }

                // 2. DomainController 特性判定
                if (FindAttribute(m.Attributes, "DomainControllerAttribute") != null)
                {
                    m.Type = MetaType.Controller;
                    filteredList.Add(m);
                    continue;
                }

                // 3. IDomainService 接口判定
                if (ImplementsInterface(m, "IDomainService"))
                {
                    bool isDecoBase = (m.BaseType != null && m.BaseType.Contains("DecoratorBase"));
                    m.Type = isDecoBase ? MetaType.Decorator : MetaType.Service;
                    filteredList.Add(m);
                    continue;
                }
            }

            allMetadatas = filteredList;
            var decorators = allMetadatas.Where(x => x.Type == MetaType.Decorator).ToDictionary(x => x.ClassName, x => x);

            // --- 第二步：建立关联与计算 Hash ---
            using (var sha = SHA256.Create())
            {
                foreach (var m in allMetadatas.Where(x => x.Type == MetaType.Entity || x.Type == MetaType.View))
                {
                    // 检查是否存在匹配的 Service/Controller，存入 Settings 供模板使用
                    var hasService = allMetadatas.Any(x => x.ClassName == $"{m.ClassName}Service" && x.Type == MetaType.Service);
                    var hasController = allMetadatas.Any(x => x.ClassName == $"{m.ClassName}Service" && x.Type == MetaType.Controller);

                    m.GenerateCodeSettings["HasService"] = hasService;
                    m.GenerateCodeSettings["HasController"] = hasController;

                    string expectedDecoName = $"{m.ClassName}ServiceDecorator";
                    if (decorators.TryGetValue(expectedDecoName, out var deco))
                    {
                        m.HasDecoratorCandidate = true;
                        m.DecoratorTypeFullName = deco.FullName;
                    }

                    // 构造 Hash 源字符串
                    StringBuilder sb = new StringBuilder();
                    sb.Append(m.Namespace).Append("|")
                      .Append(m.ClassName).Append("|")
                      .Append(m.Type).Append("|") // 使用 Type 代替多个布尔值
                      .Append(hasService).Append("|")
                      .Append(hasController).Append("|")
                      .Append(m.HasDecoratorCandidate).Append("|")
                      .Append(m.DecoratorTypeFullName);

                    byte[] bytes = Encoding.UTF8.GetBytes(sb.ToString());
                    m.SourceHash = BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-", "").ToLowerInvariant();
                }
            }
        }

        #region --- Helper Functions (Std 2.0 兼容) ---
        public static bool GetBoolProp(AttributeMetadata attr, string key, bool defaultValue)
        {
            if (attr != null && attr.Properties.TryGetValue(key, out var val))
                return val is bool b ? b : (val != null && val.ToString() != null && val.ToString().Equals("true", StringComparison.OrdinalIgnoreCase));
            return defaultValue;
        }

        private AttributeMetadata FindAttribute(IEnumerable<AttributeMetadata> attrs, string targetName)
        {
            if (attrs == null) return null;
            foreach (var a in attrs)
            {
                if (!string.IsNullOrEmpty(a.TypeFullName) &&
                    a.TypeFullName.IndexOf(targetName, StringComparison.OrdinalIgnoreCase) >= 0)
                    return a;
            }
            return null;
        }

        private bool ImplementsInterface(ClassMetadata m, string interfaceName)
        {
            if (m.ImplementedInterfaces == null) return false;
            foreach (var i in m.ImplementedInterfaces)
            {
                if (!string.IsNullOrEmpty(i) &&
                    i.IndexOf(interfaceName, StringComparison.OrdinalIgnoreCase) >= 0)
                    return true;
            }
            return false;
        }

        #endregion
    }
}