using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace xCodeGen.SourceGenerator
{
    [Generator]
    public class DomainMapFromGenerator : IIncrementalGenerator
    {
        // 定义警告：没有 partial 关键字
        private static readonly DiagnosticDescriptor NotPartialWarning = new(
            id: "TKWMAP001",
            title: "DomainMapFrom target must be partial",
            messageFormat: "类 '{0}' 使用了 [DomainMapFrom] 但未声明为 partial。映射代码生成已跳过，将回退到动态表达式树。",
            category: "Usage",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 增量过滤：只寻找标记了 [DomainMapFrom] 的类
            var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
                "TKW.Framework.Common.Attributes.DomainMapFromAttribute",
                predicate: (node, _) => node is ClassDeclarationSyntax,
                transform: GetMappingContext)
                .Where(ctx => ctx != null);
            //Debugger.Launch();
            context.RegisterSourceOutput(provider, ExecuteGeneration);
        }

        private static MappingContext GetMappingContext(GeneratorAttributeSyntaxContext context, CancellationToken ct)
        {
            var classDecl = (ClassDeclarationSyntax)context.TargetNode;
            var targetSymbol = (INamedTypeSymbol)context.TargetSymbol;

            var attribute = context.Attributes.FirstOrDefault(a => a.AttributeClass?.Name.Contains("DomainMapFrom") == true);
            if (attribute == null) return null;

            // 解析 params Type[] sourceTypes
            var sourceSymbols = new List<INamedTypeSymbol>();
            var constructorArgs = attribute.ConstructorArguments;

            // params 数组在 Roslyn 中体现为一个 TypedConstant 数组
            if (constructorArgs.Length > 0 && !constructorArgs[0].IsNull)
            {
                foreach (var typedConstant in constructorArgs[0].Values)
                {
                    if (typedConstant.Value is INamedTypeSymbol typeSymbol)
                    {
                        sourceSymbols.Add(typeSymbol);
                    }
                }
            }

            // 核心功能：如果不传任何 Type，默认将自身加入，用于生成深拷贝 Clone
            if (sourceSymbols.Count == 0)
            {
                sourceSymbols.Add(targetSymbol);
            }

            var isPartial = classDecl.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword));

            return new MappingContext
            {
                TargetSymbol = targetSymbol,
                SourceSymbols = sourceSymbols,
                IsPartial = isPartial,
                Location = classDecl.Identifier.GetLocation()
            };
        }

        private static void ExecuteGeneration(SourceProductionContext spc, MappingContext context)
        {
            if (!context.IsPartial)
            {
                // 如果开发者忘了加 partial，抛出警告并停止生成。
                // 此时业务层不会报错，因为扩展方法会按 JIT/反射 兜底执行。
                spc.ReportDiagnostic(Diagnostic.Create(NotPartialWarning, context.Location, context.TargetSymbol.Name));
                return;
            }

            var namespaceName = context.TargetSymbol.ContainingNamespace.ToDisplayString();
            var targetClassName = context.TargetSymbol.Name;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("using System;");
            sb.AppendLine("using TKW.Framework.Common.Abstractions;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            // 构建接口实现签名：例如 public partial class UserInfo : ICopyValuesFrom<UserDto>, ICopyValuesFrom<UserInfo>
            var interfaceDeclarations = string.Join(", ", context.SourceSymbols.Select(s =>
                $"ICopyValuesFrom<{s.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>"));

            sb.AppendLine($"    public partial class {targetClassName} : {interfaceDeclarations}");
            sb.AppendLine("    {");

            var targetProps = GetPublicProperties(context.TargetSymbol)
                .Where(p => p.SetMethod != null && p.SetMethod.DeclaredAccessibility == Accessibility.Public)
                .ToList();

            foreach (var sourceSymbol in context.SourceSymbols)
            {
                var sourceFullType = sourceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                // 判断开发者是否手写了专门针对这个类型的 CopyValuesFrom
                var hasHandwrittenMethod = context.TargetSymbol.GetMembers("CopyValuesFrom")
                    .OfType<IMethodSymbol>()
                    .Any(m => m.Parameters.Length == 1 && SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type, sourceSymbol));

                if (hasHandwrittenMethod)
                {
                    sb.AppendLine($"        // Found handwritten method for {sourceSymbol.Name}, skipping generation.");
                    continue; // 跳过，让给手写方法
                }

                var sourceProps = GetPublicProperties(sourceSymbol)
                    .Where(p => p.GetMethod != null && p.GetMethod.DeclaredAccessibility == Accessibility.Public)
                    .ToList();

                // 显式接口实现，防止与手写方法签名起冲突
                sb.AppendLine($"        void ICopyValuesFrom<{sourceFullType}>.CopyValuesFrom({sourceFullType} source)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (source == null) return;");

                foreach (var tProp in targetProps)
                {
                    var sProp = sourceProps.FirstOrDefault(p =>
                        p.Name.Equals(tProp.Name, StringComparison.OrdinalIgnoreCase) &&
                        IsTypeCompatible(p.Type, tProp.Type));

                    if (sProp != null)
                    {
                        // 引用类型或 Nullable 的非空验证赋值
                        if (!sProp.Type.IsValueType || sProp.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                        {
                            sb.AppendLine($"            if (source.{sProp.Name} != null)");
                            sb.AppendLine($"                this.{tProp.Name} = source.{sProp.Name};");
                        }
                        else
                        {
                            sb.AppendLine($"            this.{tProp.Name} = source.{sProp.Name};");
                        }
                    }
                }
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{targetClassName}_Mapper.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static IEnumerable<IPropertySymbol> GetPublicProperties(INamedTypeSymbol symbol)
        {
            var current = symbol;
            while (current != null && current.SpecialType != SpecialType.System_Object)
            {
                foreach (var member in current.GetMembers().OfType<IPropertySymbol>())
                {
                    yield return member;
                }
                current = current.BaseType;
            }
        }

        private static bool IsTypeCompatible(ITypeSymbol sourceType, ITypeSymbol targetType)
        {
            if (SymbolEqualityComparer.Default.Equals(sourceType, targetType)) return true;

            var sUnderlying = (sourceType as INamedTypeSymbol)?.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
                ? ((INamedTypeSymbol)sourceType).TypeArguments[0] : sourceType;

            var tUnderlying = (targetType as INamedTypeSymbol)?.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
                ? ((INamedTypeSymbol)targetType).TypeArguments[0] : targetType;

            return SymbolEqualityComparer.Default.Equals(sUnderlying, tUnderlying);
        }

        private class MappingContext
        {
            public INamedTypeSymbol TargetSymbol { get; set; }
            public List<INamedTypeSymbol> SourceSymbols { get; set; }
            public bool IsPartial { get; set; }
            public Location Location { get; set; }
        }
    }
}