//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKWF.ExcelImporter {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelImporter_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelImporter_en() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TKWF.ExcelImporter.ExcelImporter_en", typeof(ExcelImporter_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 字段 {0} 数据格式错误: {1} 的本地化字符串。
        /// </summary>
        internal static string FieldFormatError {
            get {
                return ResourceManager.GetString("FieldFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 {0} 映射失败: {1} 的本地化字符串。
        /// </summary>
        internal static string FieldMappingError {
            get {
                return ResourceManager.GetString("FieldMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在: {0} 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表头缺少必要列：{0} 的本地化字符串。
        /// </summary>
        internal static string HeaderMissingColumn {
            get {
                return ResourceManager.GetString("HeaderMissingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表头行读取失败 的本地化字符串。
        /// </summary>
        internal static string HeaderReadFailed {
            get {
                return ResourceManager.GetString("HeaderReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入失败: {0} 的本地化字符串。
        /// </summary>
        internal static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行数据格式错误: {1} 的本地化字符串。
        /// </summary>
        internal static string RowFormatError {
            get {
                return ResourceManager.GetString("RowFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行映射失败: {1} 的本地化字符串。
        /// </summary>
        internal static string RowMappingError {
            get {
                return ResourceManager.GetString("RowMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}行处理未知错误: {1} 的本地化字符串。
        /// </summary>
        internal static string RowUnknownError {
            get {
                return ResourceManager.GetString("RowUnknownError", resourceCulture);
            }
        }
    }
}
