using System;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using xCodeGen.Abstractions.Metadata;

namespace xCodeGen.Core.IO;

/// <summary>
/// 增量生成校验器，基于逻辑指纹判断是否需要重新生成
/// </summary>
public class IncrementalChecker(IFileWriter fileWriter)
{
    /// <summary>
    /// 判断是否需要重新生成文件。注意：即使返回 true，currentHash 也会被正确赋值。
    /// </summary>
    public bool NeedRegenerate(ClassMetadata metadata, string outputDirectory, string projectName, string pattern, string templateContent, out string currentHash)
    {
        // 🛠️ 核心：第一步就计算指纹，确保 out 参数在任何返回路径下都有值
        currentHash = ComputeLogicHash(metadata, templateContent);

        var targetFilePath = fileWriter.ResolveOutputPath(outputDirectory, projectName, pattern);

        // 如果文件不存在，必须生成
        if (!File.Exists(targetFilePath)) return true;

        try
        {
            using var reader = new StreamReader(targetFilePath);
            // 扫描前 15 行寻找指纹标记（稍微放宽范围以应对较长的文件头）
            for (var i = 0; i < 15; i++)
            {
                var line = reader.ReadLine();
                if (line == null) break;

                // 对比：文件标记中是否包含当前逻辑指纹
                // 标记格式通常为：// <auto-generated> [xCodeGen.Hash: 1234567890ABCDEF] </auto-generated>
                if (line.Contains("[xCodeGen.Hash:") && line.Contains(currentHash))
                    return false;
            }
        }
        catch
        {
            // 读取失败（如文件被占用）则稳妥起见强制生成
            return true;
        }

        return true;
    }

    public static string ComputeLogicHash(ClassMetadata metadata, string templateContent)
    {
        var sb = new StringBuilder();
        // 1. 元数据维度：包含类名、命名空间、注释及属性结构
        sb.Append($"{metadata.Namespace}.{metadata.ClassName}:{metadata.Summary};");
        foreach (var p in metadata.Properties.OrderBy(p => p.Name))
        {
            sb.Append($"{p.Name}:{p.TypeName}:{p.Summary};");
            foreach (var a in p.Attributes.OrderBy(at => at.TypeFullName))
                sb.Append($"[{a.TypeFullName}];");
        }

        // 2. 模板维度：防止模板文件改动后不生效
        sb.Append($"|T:{GetStableHash(templateContent)}");

        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(sb.ToString()));
        // 取 16 位长度的 Hex 字符串作为指纹
        return Convert.ToHexString(bytes).Substring(0, 16);
    }

    /// <summary>
    /// 判断是否需要重新生成文件。注意：即使返回 true，currentHash 也会被正确赋值。
    /// </summary>
    public bool NeedRegenerate(IProjectMetaContext context, string outputDirectory, string itemName, string pattern, string templateContent, out string currentHash)
    {
        // 🛠️ 1. 计算逻辑指纹：包含元数据 SourceHash + 模板特征
        currentHash = ComputeLogicHash(context, templateContent);

        // 2. 解析目标物理路径
        var targetFilePath = fileWriter.ResolveOutputPath(outputDirectory, itemName, pattern);

        // 3. 基础检查
        if (!File.Exists(targetFilePath)) return true;

        try
        {
            // 4. 快速指纹比对：由于 V4 产物头部都有 // @[xCodeGen.Hash: xxx]
            // 建议使用更严谨的正则或简单的 Line.Contains
            using var reader = new StreamReader(targetFilePath);
            for (var i = 0; i < 15; i++)
            {
                var line = reader.ReadLine();
                if (line == null) break;

                // 检查逻辑：只要文件中包含计算出的 currentHash，说明元数据和模板均未变化
                if (line.Contains("[xCodeGen.Hash:") && line.Contains(currentHash))
                    return false;
            }
        }
        catch
        {
            return true; // 读取异常强制重新生成
        }

        return true;
    }

    private string ComputeLogicHash(IProjectMetaContext context, string templateContent)
    {
        using var sha = System.Security.Cryptography.SHA256.Create();
        var sb = new StringBuilder();

        // 1. 注入模板内容 (确保模板变了也重发)
        sb.Append(templateContent);

        // 2. 注入元数据特征
        if (context is IProjectMetaContext project)
        {
            // 项目级：所有实体的 SourceHash 累加（确保任何一个实体变了，全景图就更新）
            foreach (var m in project.AllMetadatas.OrderBy(x => x.FullName))
            {
                sb.Append(m.SourceHash);
            }
        }
        else if (context is ClassMetadata metadata)
        {
            // 实体级：仅关注当前实体的 SourceHash
            sb.Append(metadata.SourceHash);
        }

        var bytes = Encoding.UTF8.GetBytes(sb.ToString());
        var hashBytes = sha.ComputeHash(bytes);
        return BitConverter.ToString(hashBytes).Replace("-", "").ToLowerInvariant();
    }

    private static string GetStableHash(string input)
    {
        if (string.IsNullOrEmpty(input)) return "0";
        // 规范化：移除空格并统一换行符，减少因格式化导致的哈希抖动
        var normalized = input.Replace("\r\n", "\n").Replace("\r", "\n").Trim();
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(normalized));
        return Convert.ToHexString(bytes).Substring(0, 8);
    }
}