//------------------------------------------------------------------------------
// <auto-generated>
// 注意：此文件自动生成，用于从数据库生成 DbContext，重新生成时会被自动覆盖，不建议手工维护。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using TKW.Framework.Domain;
using TKW.Framework.Common.Extensions;
using TKW.Framework.Common.Entity.Interfaces;
using TKW.Framework.EntityFramework;
using Autofac;
using Autofac.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace DomainTest.Models
{

    public class DomainTestDataAccessHelper : IDomainDataAccessHelper
    {
        private readonly string _ConnectionString;
        public DomainTestDataAccessHelper(string connectionString)
        {
            _ConnectionString = connectionString.EnsureHasValue(nameof(connectionString));
            DepartmentRepository = new EfCoreRepository<DomainTestContext, Department>(CreateDbContextInstance<DomainTestContext>);
            StaffRepository = new EfCoreRepository<DomainTestContext, Staff>(CreateDbContextInstance<DomainTestContext>);
            VStaffRepository = new EfCoreViewRepository<DomainTestContext, VStaff>(CreateDbContextInstance<DomainTestContext>);
        }
        /// <exception cref="Exception">A delegate callback throws an exception.</exception>
        public TDbContext CreateDbContextInstance<TDbContext>()
            where TDbContext : DbContext, IEntityDbContext
        {
            return new DomainTestContext(_ConnectionString) as TDbContext;
        }
        internal EfCoreRepository<DomainTestContext, Department> DepartmentRepository { get; }
        public EfCoreRepository<DomainTestContext, Staff> StaffRepository { get; }
        internal EfCoreViewRepository<DomainTestContext, VStaff> VStaffRepository { get; }
    }

    public static class DomainTestContextExtension
    {
        public static IRegistrationBuilder<IDomainDataAccessHelper, SimpleActivatorData, SingleRegistrationStyle> AddDomainTestDataAccessHelper(this ContainerBuilder containerBuilder, string connectionString)
        {
            return containerBuilder.AddDomainDataAccessHelper(new DomainTestDataAccessHelper(connectionString));
        }

        /*
        //TODO: 尚未测试
        public static IRegistrationBuilder<DbContextOptions, SimpleActivatorData, SingleRegistrationStyle> AddDomainTestDataAccessHelper2(this ContainerBuilder containerBuilder, string connectionString, string dbContextName = null)
        {
            return containerBuilder.RegisterInstance(
                    new DbContextOptionsBuilder().UseSqlServer(connectionString).Options)
                .Named<DbContextOptions>(dbContextName ?? "DomainTestContext");
        }

        public static IRegistrationBuilder<DbContextFactoryDelegate, SimpleActivatorData, SingleRegistrationStyle> AddDomainTestDataAccessHelper3(this ContainerBuilder containerBuilder, string connectionString, string dbContextName = null)
        {
            //此方式最简单直接，但缺点在于构造 Manager 时就初始化了一个 DbContext，可能未使用且未必能被正确释放
            //最好的方式是传入 DbContext 的类厂，由 Manager 在具体方法中创建并释放实例。
            //更好：使用上 EFCore 的连接池机制
            return containerBuilder.RegisterInstance<DbContextFactoryDelegate>(() => new DomainTestContext(connectionString))
                .Named<DbContextFactoryDelegate>(dbContextName ?? "DomainTestContext");
        }
        public delegate DbContext DbContextFactoryDelegate();
        */
    }
    public partial class DomainTestContext : DbContext, IEntityDbContext
    {

        private readonly string _ConnectionString;

        public DomainTestContext(string connectionString) :
            base()
        {
            _ConnectionString = connectionString.EnsureHasValue(nameof(connectionString));
            OnCreated();
        }
        //创建 Model 类的属性

        public DomainTestContext(DbContextOptions<DomainTestContext> options) :
            base(options)
        {
            OnCreated();
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer(_ConnectionString);
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        //public IQueryable<Department> DepartmentsQueryable => Departments.AsQueryable();
        internal DbSet<Department> Departments
        {
            get;
            set;
        }

        //public IQueryable<Staff> StaffsQueryable => Staffs.AsQueryable();
        public DbSet<Staff> Staffs
        {
            get;
            set;
        }

        public IQueryable<VStaff> VStaffsQueryable => VStaffs.AsQueryable();
        internal DbSet<VStaff> VStaffs
        {
            get;
            set;
        }
        public DbSet<T> GetDbSet<T>() where T : class, IEntityModel
        {
            var type = typeof(T);
            if (type == typeof(Department))
                return Departments as DbSet<T>;
            if (type == typeof(Staff))
                return Staffs as DbSet<T>;
            if (type == typeof(VStaff))
                return VStaffs as DbSet<T>;

            throw new NotSupportedException($"暂不支持的类型：{type}");
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            this.DepartmentMapping(modelBuilder);
            this.CustomizeDepartmentMapping(modelBuilder);

            this.StaffMapping(modelBuilder);
            this.CustomizeStaffMapping(modelBuilder);

            this.VStaffMapping(modelBuilder);
            this.CustomizeVStaffMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region Department Mapping

        private void DepartmentMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Department>().ToTable(@"Department", @"dbo");
            modelBuilder.Entity<Department>().Property(x => x.Uid).HasColumnName(@"Uid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"newid()");
            modelBuilder.Entity<Department>().Property(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Department>().Property(x => x.Name).HasColumnName(@"Name").HasColumnType(@"nvarchar(20)").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Department>().Property(x => x.IsRoot).HasColumnName(@"IsRoot").HasColumnType(@"bit").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"0");
            modelBuilder.Entity<Department>().Property(x => x.ParentDeptUid).HasColumnName(@"ParentDeptUid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Department>().Property(x => x.DateTimeCreated).HasColumnName(@"DateTimeCreated").HasColumnType(@"datetime").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Department>().HasKey(@"Uid");
        }

        partial void CustomizeDepartmentMapping(ModelBuilder modelBuilder);

        #endregion

        #region Staff Mapping

        private void StaffMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Staff>().ToTable(@"Staff", @"dbo");
            modelBuilder.Entity<Staff>().Property(x => x.Uid).HasColumnName(@"Uid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"newid()");
            modelBuilder.Entity<Staff>().Property(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Staff>().Property(x => x.Name).HasColumnName(@"Name").HasColumnType(@"nvarchar(20)").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Staff>().Property(x => x.PasswordHashed).HasColumnName(@"PasswordHashed").HasColumnType(@"varchar(64)").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            modelBuilder.Entity<Staff>().Property(x => x.Birthday).HasColumnName(@"Birthday").HasColumnType(@"datetime2").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Staff>().Property(x => x.Gender).HasColumnName(@"Gender").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Staff>().Property(x => x.DepartmentUid).HasColumnName(@"DepartmentUid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Staff>().Property(x => x.DateTimeCreated).HasColumnName(@"DateTimeCreated").HasColumnType(@"datetime").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Staff>().HasKey(@"Uid");
        }

        partial void CustomizeStaffMapping(ModelBuilder modelBuilder);

        #endregion

        #region VStaff Mapping

        private void VStaffMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VStaff>().HasNoKey();
            modelBuilder.Entity<VStaff>().ToView(@"VStaff", @"dbo");
            modelBuilder.Entity<VStaff>().Property(x => x.Uid).HasColumnName(@"Uid").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<VStaff>().Property(x => x.Name).HasColumnName(@"Name").HasColumnType(@"nvarchar(20)").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<VStaff>().Property(x => x.Birthday).HasColumnName(@"Birthday").HasColumnType(@"datetime2").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<VStaff>().Property(x => x.Gender).HasColumnName(@"Gender").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<VStaff>().Property(x => x.DeptName).HasColumnName(@"DeptName").HasColumnType(@"nvarchar(20)").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<VStaff>().Property(x => x.DateTimeCreated).HasColumnName(@"DateTimeCreated").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
        }

        partial void CustomizeVStaffMapping(ModelBuilder modelBuilder);

        #endregion
        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Department>().HasMany(x => x.SubDepts).WithOne(op => op.ParentDept).HasForeignKey(@"ParentDeptUid").IsRequired(true);
            modelBuilder.Entity<Department>().HasOne(x => x.ParentDept).WithMany(op => op.SubDepts).HasForeignKey(@"ParentDeptUid").IsRequired(true);
            modelBuilder.Entity<Department>().HasMany(x => x.Staffs).WithOne(op => op.Department).HasForeignKey(@"DepartmentUid").IsRequired(true);

            modelBuilder.Entity<Staff>().HasOne(x => x.Department).WithMany(op => op.Staffs).HasForeignKey(@"DepartmentUid").IsRequired(true);
        }
        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
