//------------------------------------------------------------------------------
// <auto-generated>
// 注意：此文件自动生成，用于从数据库生成 Model，重新生成时会被自动覆盖，不建议手工维护。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections.Generic;
using TKW.Framework.Common.Entity.Interfaces;
using TKW.Framework.Common.Extensions;
using TKW.Framework.Common.Validation;
using FluentValidation;
using FluentValidation.Results;

namespace DomainTest.Models
{
    public partial class Staff: IEntityModel, IEntityModifiable

    {
        //EntityModel 默认构造器：基于 表 的 Model
        public Staff()
        {
            //设置默认值
            SetDefaultValue();

            //触发事件
            OnCreated();
        }
        private void SetDefaultValue()
        {
          //TODO: 生成的属性默认值
        }

        public event ModelValidatedEventDelegate ModelValidatedEvent;
        public ValidationResult ValidateModel()
        {
            //TODO: 加入业务验证代码，推荐用 FluentValidation 而非声明式约束
            //TODO: 生成的默认验证
            var validator = new FluentValidation.InlineValidator<Staff>();
            //Uid,  sqlType: "uniqueidentifier",  SqlDefaultValue(@"newid()")
            validator.RuleFor(x=>x.Uid).NotNull();//.WithErrorCode("").WithMessage("");
            //Id,  sqlType: "int"
            validator.RuleFor(x=>x.Id).NotNull();//.WithErrorCode("").WithMessage("");
            //Name,  sqlType: "nvarchar(20)"
            validator.RuleFor(x=>x.Name).NotNull().NotEmpty().MaximumLength(20);//.WithErrorCode("").WithMessage("");
            //PasswordHashed,  sqlType: "varchar(64)"
            validator.RuleFor(x=>x.PasswordHashed).NotNull().NotEmpty().MaximumLength(64);//.WithErrorCode("").WithMessage("");
            //Birthday,  sqlType: "datetime2"
            validator.RuleFor(x=>x.Birthday).NotNull();//.WithErrorCode("").WithMessage("");
            //Gender,  sqlType: "int"
            validator.RuleFor(x=>x.Gender).NotNull();//.WithErrorCode("").WithMessage("");
            //DepartmentUid,  sqlType: "uniqueidentifier"
            validator.RuleFor(x=>x.DepartmentUid).NotNull();//.WithErrorCode("").WithMessage("");
            //DateTimeCreated,  sqlType: "datetime",  SqlDefaultValue(@"getdate()")
            validator.RuleFor(x=>x.DateTimeCreated).NotNull();//.WithErrorCode("").WithMessage("");
            //返回验证结果
            return validator.Validate(this).RaiseEvent(this, ModelValidatedEvent);
        }

        #region EntityModel 属性 开始
        public Guid Uid { get; set; }

        public int Id { get; set; }

        public string Name { get; set; }

        public string PasswordHashed { get; set; }

        public DateTime Birthday { get; set; }

        public int Gender { get; set; }

        public Guid DepartmentUid { get; set; }

        public DateTime DateTimeCreated { get; set; }
        #endregion EntityModel 属性结束

        #region EntityModel 导航属性 开始

        public Department Department { get; set; }
        #endregion EntityModel 导航属性结束

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
        #region CopyValues 相关方法
        //复制值的构造器
        public Staff(Staff copyFromModel) : this()
        {
            copyFromModel.AssertNotNull(nameof(copyFromModel));
            CopyValues(copyFromModel, this);
        }

        public Staff CopyValuesFrom(Staff fromModel, int level = 0)
        {
            return CopyValues(fromModel, this);
        }

        public static Staff CopyValues(Staff fromModel, Staff toModel, int level = 0)
        {
            fromModel.AssertNotNull(nameof(fromModel));
            toModel.AssertNotNull(nameof(toModel));
            toModel.Uid = fromModel.Uid;
            toModel.Id = fromModel.Id;
            toModel.Name = fromModel.Name;
            toModel.PasswordHashed = fromModel.PasswordHashed;
            toModel.Birthday = fromModel.Birthday;
            toModel.Gender = fromModel.Gender;
            toModel.DepartmentUid = fromModel.DepartmentUid;
            toModel.DateTimeCreated = fromModel.DateTimeCreated;
            //TODO: 复制导航属性值
            if (level > 0) {
              //toModel.Department = fromModel.Department.ToModel(level - 1);
            }
            return toModel;
        }

        public Staff ToModel(int level = 0)
        {
            return CopyValues(this, new Staff(), level);
        }
        public DomainTest.Staff ToEntity(int level = 0)
        {
            return new DomainTest.Staff(this);
        }
        #endregion
    }

    /// <summary>
    /// 针对 Staff 集合的扩展方法
    /// </summary>
    public static partial class StaffExtensions 
    {
        internal static List<DomainTest.Staff> ToEntities(this IEnumerable<Staff> source, int level = 0)
        {
            return source.AssertNotNull(nameof(source))
              .Select(src => src.ToEntity(level))
              .ToList();
        }

        internal static List<Staff> ToModels(this IEnumerable<DomainTest.Staff> source, int level = 0)
        {
            return source.AssertNotNull(nameof(source))
              .Select(src => src.ToModel(level))
              .ToList();
        }
    }

}
