//------------------------------------------------------------------------------
// <auto-generated>
// 注意：此文件自动生成，用于从数据库生成 Model，重新生成时会被自动覆盖，不建议手工维护。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections.Generic;
using TKW.Framework.Common.Entity.Interfaces;
using TKW.Framework.Common.Extensions;
using TKW.Framework.Common.Validation;
using FluentValidation;
using FluentValidation.Results;

namespace DomainTest.Models
{
    public partial class VStaff: IEntityModel

    {
        //EntityModel 默认构造器：基于 视图 的 Model
        public VStaff()
        {
            //设置默认值
            SetDefaultValue();

            //触发事件
            OnCreated();
        }
        private void SetDefaultValue()
        {
          //TODO: 生成的属性默认值
        }

        public event ModelValidatedEventDelegate ModelValidatedEvent;
        public ValidationResult ValidateModel()
        {
            //TODO: 加入业务验证代码，推荐用 FluentValidation 而非声明式约束
            //TODO: 生成的默认验证
            var validator = new FluentValidation.InlineValidator<VStaff>();
            //Uid,  sqlType: "uniqueidentifier"
            validator.RuleFor(x=>x.Uid).NotNull();//.WithErrorCode("").WithMessage("");
            //Name,  sqlType: "nvarchar(20)"
            validator.RuleFor(x=>x.Name).NotNull().NotEmpty().MaximumLength(20);//.WithErrorCode("").WithMessage("");
            //Birthday,  sqlType: "datetime2"
            validator.RuleFor(x=>x.Birthday).NotNull();//.WithErrorCode("").WithMessage("");
            //Gender,  sqlType: "int"
            validator.RuleFor(x=>x.Gender).NotNull();//.WithErrorCode("").WithMessage("");
            //DeptName,  sqlType: "nvarchar(20)"
            validator.RuleFor(x=>x.DeptName).NotNull().NotEmpty().MaximumLength(20);//.WithErrorCode("").WithMessage("");
            //DateTimeCreated,  sqlType: "datetime"
            validator.RuleFor(x=>x.DateTimeCreated).NotNull();//.WithErrorCode("").WithMessage("");
            //返回验证结果
            return validator.Validate(this).RaiseEvent(this, ModelValidatedEvent);
        }

        #region EntityModel 属性 开始
        public Guid Uid { get; set; }

        public string Name { get; set; }

        public DateTime Birthday { get; set; }

        public int Gender { get; set; }

        public string DeptName { get; set; }

        public DateTime DateTimeCreated { get; set; }
        #endregion EntityModel 属性结束

        #region EntityModel 导航属性 开始
        #endregion EntityModel 导航属性结束

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
        #region CopyValues 相关方法
        //复制值的构造器
        public VStaff(VStaff copyFromModel) : this()
        {
            copyFromModel.AssertNotNull(nameof(copyFromModel));
            CopyValues(copyFromModel, this);
        }

        public VStaff CopyValuesFrom(VStaff fromModel, int level = 0)
        {
            return CopyValues(fromModel, this);
        }

        public static VStaff CopyValues(VStaff fromModel, VStaff toModel, int level = 0)
        {
            fromModel.AssertNotNull(nameof(fromModel));
            toModel.AssertNotNull(nameof(toModel));
            toModel.Uid = fromModel.Uid;
            toModel.Name = fromModel.Name;
            toModel.Birthday = fromModel.Birthday;
            toModel.Gender = fromModel.Gender;
            toModel.DeptName = fromModel.DeptName;
            toModel.DateTimeCreated = fromModel.DateTimeCreated;
            //TODO: 复制导航属性值
            if (level > 0) {
            }
            return toModel;
        }

        public VStaff ToModel(int level = 0)
        {
            return CopyValues(this, new VStaff(), level);
        }
        #endregion
    }

}
