//------------------------------------------------------------------------------
// <auto-generated>
// 注意：此文件自动生成，用于从数据库生成 Model，重新生成时会被自动覆盖，不建议手工维护。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections.Generic;
using TKW.Framework.Common.Entity.Interfaces;
using TKW.Framework.Common.Extensions;
using TKW.Framework.Common.Validation;
using FluentValidation;
using FluentValidation.Results;

namespace DomainTest.Models
{
    public partial class Department: IEntityModel, IEntityModifiable

    {
        //EntityModel 默认构造器：基于 表 的 Model
        public Department()
        {
            this.SubDepts = new List<Department>();
            this.Staffs = new List<Staff>();
            //设置默认值
            SetDefaultValue();

            //触发事件
            OnCreated();
        }
        private void SetDefaultValue()
        {
          //TODO: 生成的属性默认值
        }

        public event ModelValidatedEventDelegate ModelValidatedEvent;
        public ValidationResult ValidateModel()
        {
            //TODO: 加入业务验证代码，推荐用 FluentValidation 而非声明式约束
            //TODO: 生成的默认验证
            var validator = new FluentValidation.InlineValidator<Department>();
            //Uid,  sqlType: "uniqueidentifier",  SqlDefaultValue(@"newid()")
            validator.RuleFor(x=>x.Uid).NotNull();//.WithErrorCode("").WithMessage("");
            //Id,  sqlType: "int"
            validator.RuleFor(x=>x.Id).NotNull();//.WithErrorCode("").WithMessage("");
            //Name,  sqlType: "nvarchar(20)"
            validator.RuleFor(x=>x.Name).NotNull().NotEmpty().MaximumLength(20);//.WithErrorCode("").WithMessage("");
            //IsRoot,  sqlType: "bit",  SqlDefaultValue(@"0")
            validator.RuleFor(x=>x.IsRoot).NotNull();//.WithErrorCode("").WithMessage("");
            //ParentDeptUid,  sqlType: "uniqueidentifier"
            validator.RuleFor(x=>x.ParentDeptUid).NotNull();//.WithErrorCode("").WithMessage("");
            //DateTimeCreated,  sqlType: "datetime",  SqlDefaultValue(@"getdate()")
            validator.RuleFor(x=>x.DateTimeCreated).NotNull();//.WithErrorCode("").WithMessage("");
            //返回验证结果
            return validator.Validate(this).RaiseEvent(this, ModelValidatedEvent);
        }

        #region EntityModel 属性 开始
        public Guid Uid { get; set; }

        public int Id { get; set; }

        public string Name { get; set; }

        public bool IsRoot { get; set; }

        public Guid ParentDeptUid { get; set; }

        public DateTime DateTimeCreated { get; set; }
        #endregion EntityModel 属性结束

        #region EntityModel 导航属性 开始

        public IList<Department> SubDepts { get; set; }

        public Department ParentDept { get; set; }

        public IList<Staff> Staffs { get; set; }
        #endregion EntityModel 导航属性结束

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
        #region CopyValues 相关方法
        //复制值的构造器
        public Department(Department copyFromModel) : this()
        {
            copyFromModel.AssertNotNull(nameof(copyFromModel));
            CopyValues(copyFromModel, this);
        }

        public Department CopyValuesFrom(Department fromModel, int level = 0)
        {
            return CopyValues(fromModel, this);
        }

        public static Department CopyValues(Department fromModel, Department toModel, int level = 0)
        {
            fromModel.AssertNotNull(nameof(fromModel));
            toModel.AssertNotNull(nameof(toModel));
            toModel.Uid = fromModel.Uid;
            toModel.Id = fromModel.Id;
            toModel.Name = fromModel.Name;
            toModel.IsRoot = fromModel.IsRoot;
            toModel.ParentDeptUid = fromModel.ParentDeptUid;
            toModel.DateTimeCreated = fromModel.DateTimeCreated;
            //TODO: 复制导航属性值
            if (level > 0) {
              //toModel.SubDepts = fromModel.SubDepts.ToModels(level - 1);
              //toModel.ParentDept = fromModel.ParentDept.ToModel(level - 1);
              //toModel.Staffs = fromModel.Staffs.ToModels(level - 1);
            }
            return toModel;
        }

        public Department ToModel(int level = 0)
        {
            return CopyValues(this, new Department(), level);
        }
        #endregion
    }

}
