//------------------------------------------------------------------------------
// <auto-generated>
// 注意：此文件自动生成，用于为 Model 提供的 Entity，重新生成时会被自动覆盖，不建议手工维护。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using TKW.Framework.Common.Entity.Interfaces;
using TKW.Framework.Common.Extensions;
using DomainTest.Models;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace DomainTest
{

    public partial class Staff: IEntityObject
    {
        #region Constructors

        internal Models.Staff _Model;
        public Staff() 
        {
            _Model = new Models.Staff();
        }

        internal Staff(Models.Staff model, int level = 0) : this()
        {
            Models.Staff.CopyValues(model.AssertNotNull(), _Model, level);
        }

        public Staff(Staff copyFromEntity, int level = 0) : this()
        {
            copyFromEntity.AssertNotNull();
            CopyValues(copyFromEntity, this);
        }

        //全属性构造器  //TODO: 过滤只读属性和忽略属性
        public Staff(System.Guid uid, int id, string name, string passwordHashed, System.DateTime birthday, int gender, System.Guid departmentUid, System.DateTime dateTimeCreated) : this()
        {
            _Model.Uid = uid;
            _Model.Id = id;
            _Model.Name = name;
            _Model.PasswordHashed = passwordHashed;
            _Model.Birthday = birthday;
            _Model.Gender = gender;
            _Model.DepartmentUid = departmentUid;
            _Model.DateTimeCreated = dateTimeCreated;
        }
        #endregion

        #region 验证数据
        /// <summary>
        /// 根据业务规则验证数据：暂时在基础框架引入 FluentValidation 包，未来考虑去掉
        /// </summary>
        public FluentValidation.Results.ValidationResult ValidateValues()
        {
            //_Model 自带的基础验证
            var errors = _Model.ValidateModel();
            return errors.IsValid 
                ? OnValidateValues() //进一步验证业务规则
                : errors;
        }
        #endregion

        #region Properties

        [Key]
        [Required()]
        public System.Guid Uid 
        { 
            get
            {
                return _Model.Uid;
            }
            set
            {
                _Model.Uid = value;
            }
        }

        [Required()]
        public int Id 
        { 
            get
            {
                return _Model.Id;
            }
            set
            {
                _Model.Id = value;
            }
        }

        [StringLength(20)]
        [Required()]
        public string Name 
        { 
            get
            {
                return _Model.Name;
            }
            set
            {
                _Model.Name = value;
            }
        }

        [StringLength(64)]
        [Required()]
        public string PasswordHashed 
        { 
            get
            {
                return _Model.PasswordHashed;
            }
            set
            {
                _Model.PasswordHashed = value;
            }
        }

        [Required()]
        public System.DateTime Birthday 
        { 
            get
            {
                return _Model.Birthday;
            }
            set
            {
                _Model.Birthday = value;
            }
        }

        [Required()]
        public int Gender 
        { 
            get
            {
                return _Model.Gender;
            }
            set
            {
                _Model.Gender = value;
            }
        }

        [Required()]
        public System.Guid DepartmentUid 
        { 
            get
            {
                return _Model.DepartmentUid;
            }
            set
            {
                _Model.DepartmentUid = value;
            }
        }

        [Required()]
        public System.DateTime DateTimeCreated 
        { 
            get
            {
                return _Model.DateTimeCreated;
            }
            set
            {
                _Model.DateTimeCreated = value;
            }
        }

        #endregion

        #region 复制值的方法
        internal Models.Staff ToModel(int level = 0)
        {
            return this._Model.ToModel(level);
        }
        
        public DomainTest.Staff ToEntity(int level = 0)
        {
            return new Staff(this, level);
        }

        public Staff CopyValuesFrom(Staff fromEntity, int level = 0)
        {
            CopyValues(fromEntity, this, level);
            OnCopyValues(fromEntity, level);
            return this;
        }
        partial void OnCopyValues(Staff fromEntity, int level = 0);


        public static Staff CopyValues(Staff fromEntity, Staff toEntity, int level = 0)
        {
            toEntity._Model.CopyValuesFrom(fromEntity._Model.AssertNotNull(), level);

            return toEntity;
        }
        #endregion
    }

}
