//------------------------------------------------------------------------------
// <auto-generated>
// 注意：此文件仅第一次自动生成，用于为 Model 提供的 Entity，可加入业务代码。
// 2022/8/12 19:11:35
// </auto-generated>
//------------------------------------------------------------------------------

using FluentValidation;
using FluentValidation.Results;
using TKW.Framework.Common.Validation;

namespace DomainTest
{

    public partial class Staff
    {
        /// <summary>
        /// 根据业务规则验证数据：暂时在基础框架引入 FluentValidation 包，未来考虑去掉
        /// </summary>
        /// <exception cref="ValidationException">验证失败异常</exception>
        private ValidationResult OnValidateValues()
        {
            //TODO: 加入业务验证代码，推荐用 FluentValidation 而非声明式约束
            var validator = new InlineValidator<Staff>();
            /*
            validator.RuleFor(d => d.Name).NotNull().NotEmpty().Length(2, 10)
                .WithMessage("部门名称不能短于2个汉字长于10个汉字");
            */
            return validator.Validate(this);
        }

        /// <summary>
        /// 根据业务规则复制数据（已调用基础的复制方法）
        /// </summary>
        /// <exception cref="ValidationException">验证失败异常</exception>
        partial void OnCopyValues(Staff fromEntity, int level)
        {
            //TODO: 加入业务所需的复制值代码
        }
    }
}
